# Generated by Django 4.2.9 on 2024-03-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
