# Generated by Django 4.2.9 on 2024-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_remove_userdata_serial_number_userdata_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='all_notes',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='favourite_notes',
            field=models.TextField(default='{}'),
        ),
    ]
