# Generated by Django 4.2.9 on 2024-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_alter_userdata_all_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='all_notes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='favourite_notes',
            field=models.JSONField(default=dict),
        ),
    ]
